remote_theme: al-folio@master
plugins:
- jekyll-remote-theme

title: Human Ethnicity Classifier
description: An image classification API that can classify 10 different ethnicity people

author: Md Maruf Chowdhury